runtime: php83
service: hushtalk-api

runtime_config:
  document_root: .

handlers:
- url: .*
  script: auto

entrypoint: 
  serve handler.php

env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: prak-tcc
  CLOUDSQL_PASSWORD: ''
  CLOUDSQL_DSN: /cloudsql/e-11-415004:asia-southeast2:database
